.TH projectM-PulseAudio 1 "June 24, 2010"
.SH NAME
projectM-pulseaudio \- ProjectM module for PulseAudio
.SH DESCRIPTION
This manual page documents the
.B projectM-pulseaudio
command.
.PP
.B projectM-pulseaudio
provides direct visualisation of PulseAudio streams using
the projectM audio visualisation library.
.PP
.B projectM-pulseaudio
can be run from the
.B Applications
menu after it was installed.
.SH AUTHOR
projectM-PulseAudio was written by Carmelo Piccione <Carmelo.Piccione+projectM@gmail.com>.
.PP
This manual page was written by Matthias Klumpp <matthias@tenstral.net>,
for the Debian project (and may be used by others).
