/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(73): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(478): ResourceLoader->preloadModuleInfo(Array, Object(ResourceLoaderContext))
#5 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#6 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderModule.php(310): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/resourceloader/ResourceLoaderFileModule.php(448): ResourceLoaderModule->getFileDependencies('vector')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(498): ResourceLoaderFileModule->getModifiedTime(Object(ResourceLoaderContext))
#6 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#7 {main}
*/
/*
exception 'DBConnectionError' with message 'DB connection error: Can't connect to MySQL server on 'db1.winamp.com' (111) (db1.winamp.com)' in /var/wiki.winamp.com/includes/db/Database.php:888
Stack trace:
#0 /var/wiki.winamp.com/includes/db/LoadBalancer.php(763): DatabaseBase->reportConnectionError('Unknown error (...')
#1 /var/wiki.winamp.com/includes/db/LoadBalancer.php(496): LoadBalancer->reportConnectionError()
#2 /var/wiki.winamp.com/includes/GlobalFunctions.php(3491): LoadBalancer->getConnection(-1, Array, false)
#3 /var/wiki.winamp.com/includes/MessageBlobStore.php(334): wfGetDB(-1)
#4 /var/wiki.winamp.com/includes/MessageBlobStore.php(51): MessageBlobStore::getFromDB(Object(ResourceLoader), Array, 'en')
#5 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(725): MessageBlobStore::get(Object(ResourceLoader), Array, 'en')
#6 /var/wiki.winamp.com/includes/resourceloader/ResourceLoader.php(517): ResourceLoader->makeModuleResponse(Object(ResourceLoaderContext), Array, Array)
#7 /var/wiki.winamp.com/load.php(43): ResourceLoader->respond(Object(ResourceLoaderContext))
#8 {main}
*/
mw.loader.implement("jquery.autoEllipsis",function(){(function($){var cache={},matchTextCache={};$.fn.autoEllipsis=function(options){options=$.extend({position:'center',tooltip:false,restoreText:false,hasSpan:false,matchText:null},options);return this.each(function(){var $trimmableText,text,trimmableText,w,pw,l,r,i,side,m,$container=$(this);if(options.restoreText){if(!$container.data('autoEllipsis.originalText')){$container.data('autoEllipsis.originalText',$container.text());}else{$container.text($container.data('autoEllipsis.originalText'));}}if(options.hasSpan){$trimmableText=$container.children(options.selector);}else{$trimmableText=$('<span>').css('whiteSpace','nowrap').text($container.text());$container.empty().append($trimmableText);}text=$container.text();trimmableText=$trimmableText.text();w=$container.width();pw=0;if(options.matchText){if(!(text in matchTextCache)){matchTextCache[text]={};}if(!(options.matchText in matchTextCache[text])){matchTextCache[text][options.matchText]
={};}if(!(w in matchTextCache[text][options.matchText])){matchTextCache[text][options.matchText][w]={};}if(options.position in matchTextCache[text][options.matchText][w]){$container.html(matchTextCache[text][options.matchText][w][options.position]);if(options.tooltip){$container.attr('title',text);}return;}}else{if(!(text in cache)){cache[text]={};}if(!(w in cache[text])){cache[text][w]={};}if(options.position in cache[text][w]){$container.html(cache[text][w][options.position]);if(options.tooltip){$container.attr('title',text);}return;}}if($trimmableText.width()+pw>w){switch(options.position){case'right':l=0;r=trimmableText.length;do{m=Math.ceil((l+r)/2);$trimmableText.text(trimmableText.substr(0,m)+'...');if($trimmableText.width()+pw>w){r=m-1;}else{l=m;}}while(l<r);$trimmableText.text(trimmableText.substr(0,l)+'...');break;case'center':i=[Math.round(trimmableText.length/2),Math.round(trimmableText.length/2)];side=1;while($trimmableText.outerWidth()+pw>w&&i[0]>0){$trimmableText.text(
trimmableText.substr(0,i[0])+'...'+trimmableText.substr(i[1]));if(side===0){i[0]--;side=1;}else{i[1]++;side=0;}}break;case'left':r=0;while($trimmableText.outerWidth()+pw>w&&r<trimmableText.length){$trimmableText.text('...'+trimmableText.substr(r));r++;}break;}}if(options.tooltip){$container.attr('title',text);}if(options.matchText){$container.highlightText(options.matchText);matchTextCache[text][options.matchText][w][options.position]=$container.html();}else{cache[text][w][options.position]=$container.html();}});};}(jQuery));;},{},{});mw.loader.implement("jquery.checkboxShiftClick",function(){(function($){$.fn.checkboxShiftClick=function(){var prevCheckbox=null,$box=this;$box.click(function(e){if(prevCheckbox!==null&&e.shiftKey){$box.slice(Math.min($box.index(prevCheckbox),$box.index(e.target)),Math.max($box.index(prevCheckbox),$box.index(e.target))+1).filter(function(){return!this.disabled;}).prop('checked',!!e.target.checked);}prevCheckbox=e.target;});return $box;};}(jQuery));;},{},{
});mw.loader.implement("jquery.hidpi",function(){(function($){$.devicePixelRatio=function(){if(window.devicePixelRatio!==undefined){return window.devicePixelRatio;}else if(window.msMatchMedia!==undefined){if(window.msMatchMedia('(min-resolution: 192dpi)').matches){return 2;}else if(window.msMatchMedia('(min-resolution: 144dpi)').matches){return 1.5;}else{return 1;}}else{return 1;}};$.fn.hidpi=function(){var $target=this,devicePixelRatio=$.devicePixelRatio(),testImage=new Image();if(devicePixelRatio>1&&testImage.srcset===undefined){$target.find('img').each(function(){var $img=$(this),srcset=$img.attr('srcset'),match;if(typeof srcset==='string'&&srcset!==''){match=$.matchSrcSet(devicePixelRatio,srcset);if(match!==null){$img.attr('src',match);}}});}return $target;};$.matchSrcSet=function(devicePixelRatio,srcset){var candidates,candidate,bits,src,i,ratioStr,ratio,selectedRatio=1,selectedSrc=null;candidates=srcset.split(/ *, */);for(i=0;i<candidates.length;i++){candidate=candidates[i];bits=
candidate.split(/ +/);src=bits[0];if(bits.length>1&&bits[1].charAt(bits[1].length-1)==='x'){ratioStr=bits[1].substr(0,bits[1].length-1);ratio=parseFloat(ratioStr);if(ratio<=devicePixelRatio&&ratio>selectedRatio){selectedRatio=ratio;selectedSrc=src;}}}return selectedSrc;};}(jQuery));;},{},{});mw.loader.implement("jquery.highlightText",function(){(function($){$.highlightText={splitAndHighlight:function(node,pat){var i,patArray=pat.split(' ');for(i=0;i<patArray.length;i++){if(patArray[i].length===0){continue;}$.highlightText.innerHighlight(node,patArray[i]);}return node;},innerHighlight:function(node,pat){var i,match,pos,spannode,middlebit,middleclone;if(node.nodeType===3){match=node.data.match(new RegExp('(^|\\s)'+$.escapeRE(pat),'i'));if(match){pos=match.index+match[1].length;spannode=document.createElement('span');spannode.className='highlight';middlebit=node.splitText(pos);middlebit.splitText(pat.length);middleclone=middlebit.cloneNode(true);spannode.appendChild(middleclone);middlebit
.parentNode.replaceChild(spannode,middlebit);}}else if(node.nodeType===1&&node.childNodes&&!/(script|style)/i.test(node.tagName)&&!(node.tagName.toLowerCase()==='span'&&node.className.match(/\bhighlight/))){for(i=0;i<node.childNodes.length;++i){$.highlightText.innerHighlight(node.childNodes[i],pat);}}}};$.fn.highlightText=function(matchString){return this.each(function(){var $el=$(this);$el.data('highlightText',{originalText:$el.text()});$.highlightText.splitAndHighlight(this,matchString);});};}(jQuery));;},{},{});mw.loader.implement("jquery.makeCollapsible",function(){(function($,mw){var lpx='jquery.makeCollapsible> ';function toggleElement($collapsible,action,$defaultToggle,options){var $collapsibleContent,$containers,hookCallback;options=options||{};if(!$collapsible.jquery){return;}if(action!=='expand'&&action!=='collapse'){return;}if($defaultToggle===undefined){$defaultToggle=null;}if($defaultToggle!==null&&!$defaultToggle.jquery){return;}$collapsible.trigger(action==='expand'?
'beforeExpand.mw-collapsible':'beforeCollapse.mw-collapsible');hookCallback=function(){$collapsible.trigger(action==='expand'?'afterExpand.mw-collapsible':'afterCollapse.mw-collapsible');};if(!options.plainMode&&$collapsible.is('table')){$containers=$collapsible.find('> tbody > tr');if($defaultToggle){$containers=$containers.not($defaultToggle.closest('tr'));}if(action==='collapse'){if(options.instantHide){$containers.hide();hookCallback();}else{$containers.stop(true,true).fadeOut().promise().done(hookCallback);}}else{$containers.stop(true,true).fadeIn().promise().done(hookCallback);}}else if(!options.plainMode&&($collapsible.is('ul')||$collapsible.is('ol'))){$containers=$collapsible.find('> li');if($defaultToggle){$containers=$containers.not($defaultToggle.parent());}if(action==='collapse'){if(options.instantHide){$containers.hide();hookCallback();}else{$containers.stop(true,true).slideUp().promise().done(hookCallback);}}else{$containers.stop(true,true).slideDown().promise().done(
hookCallback);}}else{$collapsibleContent=$collapsible.find('> .mw-collapsible-content');if(!options.plainMode&&$collapsibleContent.length){if(action==='collapse'){if(options.instantHide){$collapsibleContent.hide();hookCallback();}else{$collapsibleContent.slideUp().promise().done(hookCallback);}}else{$collapsibleContent.slideDown().promise().done(hookCallback);}}else{if(action==='collapse'){if(options.instantHide){$collapsible.hide();hookCallback();}else{if($collapsible.is('tr')||$collapsible.is('td')||$collapsible.is('th')){$collapsible.fadeOut().promise().done(hookCallback);}else{$collapsible.slideUp().promise().done(hookCallback);}}}else{if($collapsible.is('tr')||$collapsible.is('td')||$collapsible.is('th')){$collapsible.fadeIn().promise().done(hookCallback);}else{$collapsible.slideDown().promise().done(hookCallback);}}}}}function togglingHandler($toggle,$collapsible,e,options){var wasCollapsed,$textContainer,collapseText,expandText;if(options===undefined){options={};}if(e){if(e.type
==='click'&&options.linksPassthru&&$.nodeName(e.target,'a')){return;}else if(e.type==='keypress'&&e.which!==13&&e.which!==32){return;}else{e.preventDefault();e.stopPropagation();}}if(options.wasCollapsed!==undefined){wasCollapsed=options.wasCollapsed;}else{wasCollapsed=$collapsible.hasClass('mw-collapsed');}$collapsible.toggleClass('mw-collapsed',!wasCollapsed);if(options.toggleClasses){$toggle.toggleClass('mw-collapsible-toggle-collapsed',!wasCollapsed).toggleClass('mw-collapsible-toggle-expanded',wasCollapsed);}if(options.toggleText){collapseText=options.toggleText.collapseText;expandText=options.toggleText.expandText;$textContainer=$toggle.find('> a');if(!$textContainer.length){$textContainer=$toggle;}$textContainer.text(wasCollapsed?collapseText:expandText);}toggleElement($collapsible,wasCollapsed?'expand':'collapse',$toggle,options);}$.fn.makeCollapsible=function(options){if(options===undefined){options={};}return this.each(function(){var $collapsible,collapseText,expandText,
$toggle,actionHandler,buildDefaultToggleLink,premadeToggleHandler,$toggleLink,$firstItem,collapsibleId,$customTogglers,firstval;$collapsible=$(this).addClass('mw-collapsible');if($collapsible.data('mw-made-collapsible')){return;}else{$collapsible.data('mw-made-collapsible',true);}collapseText=options.collapseText||$collapsible.attr('data-collapsetext')||mw.msg('collapsible-collapse');expandText=options.expandText||$collapsible.attr('data-expandtext')||mw.msg('collapsible-expand');actionHandler=function(e,opts){var defaultOpts={toggleClasses:true,toggleText:{collapseText:collapseText,expandText:expandText}};opts=$.extend(defaultOpts,options,opts);togglingHandler($(this),$collapsible,e,opts);};buildDefaultToggleLink=function(){return $('<a href="#"></a>').text(collapseText).wrap('<span class="mw-collapsible-toggle"></span>').parent().prepend('&nbsp;[').append(']&nbsp;').on('click.mw-collapsible keypress.mw-collapsible',actionHandler);};premadeToggleHandler=function(e,opts){var defaultOpts
={toggleClasses:true,linksPassthru:true};opts=$.extend(defaultOpts,options,opts);togglingHandler($(this),$collapsible,e,opts);};if(options.$customTogglers){$customTogglers=$(options.$customTogglers);}else{collapsibleId=$collapsible.attr('id')||'';if(collapsibleId.indexOf('mw-customcollapsible-')===0){mw.log(lpx+'Found custom collapsible: #'+collapsibleId);$customTogglers=$('.'+collapsibleId.replace('mw-customcollapsible','mw-customtoggle'));if(!$customTogglers.length){mw.log(lpx+'#'+collapsibleId+': Missing toggler!');}}}if($customTogglers&&$customTogglers.length){actionHandler=function(e,opts){var defaultOpts={};opts=$.extend(defaultOpts,options,opts);togglingHandler($(this),$collapsible,e,opts);};$toggleLink=$customTogglers;$toggleLink.on('click.mw-collapsible keypress.mw-collapsible',actionHandler);}else{if($collapsible.is('table')){$firstItem=$collapsible.find('tr:first th, tr:first td');$toggle=$firstItem.find('> .mw-collapsible-toggle');if(!$toggle.length){$toggleLink=
buildDefaultToggleLink().prependTo($firstItem.eq(-1));}else{actionHandler=premadeToggleHandler;$toggleLink=$toggle.on('click.mw-collapsible keypress.mw-collapsible',actionHandler);}}else if($collapsible.is('ul')||$collapsible.is('ol')){$firstItem=$collapsible.find('li:first');$toggle=$firstItem.find('> .mw-collapsible-toggle');if(!$toggle.length){firstval=$firstItem.attr('value');if(firstval===undefined||!firstval||firstval==='-1'||firstval===-1){$firstItem.attr('value','1');}$toggleLink=buildDefaultToggleLink();$toggleLink.wrap('<li class="mw-collapsible-toggle-li"></li>').parent().prependTo($collapsible);}else{actionHandler=premadeToggleHandler;$toggleLink=$toggle.on('click.mw-collapsible keypress.mw-collapsible',actionHandler);}}else{$toggle=$collapsible.find('> .mw-collapsible-toggle');if(!$collapsible.find('> .mw-collapsible-content').length){$collapsible.wrapInner('<div class="mw-collapsible-content"></div>');}if(!$toggle.length){$toggleLink=buildDefaultToggleLink().prependTo(
$collapsible);}else{actionHandler=premadeToggleHandler;$toggleLink=$toggle.on('click.mw-collapsible keypress.mw-collapsible',actionHandler);}}}$toggleLink.prop('tabIndex',0);if(options.collapsed||$collapsible.hasClass('mw-collapsed')){actionHandler.call($toggleLink.get(0),null,{instantHide:true,wasCollapsed:false});}});};}(jQuery,mediaWiki));;},{"css":[".mw-collapsible-toggle{float:right} li .mw-collapsible-toggle{float:none} .mw-collapsible-toggle-li{list-style:none}\n/* cache key: winamp_wiki:resourceloader:filter:minify-css:7:4250852ed2349a0d4d0fc6509a3e7d4c */"]},{});mw.loader.implement("jquery.mw-jump",function(){jQuery(function($){$('.mw-jump').on('focus blur','a',function(e){if(e.type==='blur'||e.type==='focusout'){$(this).closest('.mw-jump').css({height:0});}else{$(this).closest('.mw-jump').css({height:'auto'});}});});;},{},{});mw.loader.implement("jquery.placeholder",function(){(function($){$.fn.placeholder=function(text){var hasArg=arguments.length;return this.each(function()
{var placeholder,$input;if(hasArg){this.setAttribute('placeholder',text);}if(this.placeholder&&'placeholder'in document.createElement(this.tagName)){return;}placeholder=hasArg?text:this.getAttribute('placeholder');$input=$(this);if(this.value===''||this.value===placeholder){$input.addClass('placeholder').val(placeholder);}$input.blur(function(){if(this.value===''){this.value=placeholder;$input.addClass('placeholder');}}).on('focus drop keydown paste',function(e){if($input.hasClass('placeholder')){if(e.type==='drop'&&e.originalEvent.dataTransfer){try{this.value=e.originalEvent.dataTransfer.getData('text/plain');}catch(exception){this.value=e.originalEvent.dataTransfer.getData('text');}e.preventDefault();}else{this.value='';}$input.removeClass('placeholder');}});if(this.form){$(this.form).submit(function(){if($input.hasClass('placeholder')){$input.val('').removeClass('placeholder');}});}});};}(jQuery));;},{},{});mw.loader.implement("jquery.suggestions",function(){(function($){$.
suggestions={cancel:function(context){if(context.data.timerID!==null){clearTimeout(context.data.timerID);}if($.isFunction(context.config.cancel)){context.config.cancel.call(context.data.$textbox);}},restore:function(context){context.data.$textbox.val(context.data.prevText);},update:function(context,delayed){function maybeFetch(){if(context.data.$textbox.val().length===0){context.data.$container.hide();context.data.prevText='';}else if(context.data.$textbox.val()!==context.data.prevText||!context.data.$container.is(':visible')){if(typeof context.config.fetch==='function'){context.data.prevText=context.data.$textbox.val();context.config.fetch.call(context.data.$textbox,context.data.$textbox.val());}}}$.suggestions.cancel(context);if(delayed){context.data.timerID=setTimeout(maybeFetch,context.config.delay);}else{maybeFetch();}$.suggestions.special(context);},special:function(context){if(typeof context.config.special.render==='function'){setTimeout(function(){var $special=context.data.
$container.find('.suggestions-special');context.config.special.render.call($special,context.data.$textbox.val(),context);},1);}},configure:function(context,property,value){var newCSS,$autoEllipseMe,$result,$results,childrenWidth,i,expWidth,matchedText,maxWidth,text;switch(property){case'fetch':case'cancel':case'special':case'result':case'$region':case'expandFrom':context.config[property]=value;break;case'suggestions':context.config[property]=value;if(context.data!==undefined){if(context.data.$textbox.val().length===0){context.data.$container.hide();}else{context.data.$container.show();newCSS={top:context.config.$region.offset().top+context.config.$region.outerHeight(),bottom:'auto',width:context.config.$region.outerWidth(),height:'auto'};context.config.expandFrom=(function(expandFrom){var regionWidth,docWidth,regionCenter,docCenter,docDir=$(document.documentElement).css('direction'),$region=context.config.$region;if(context.config.positionFromLeft){expandFrom='left';}else if($.inArray(
expandFrom,['left','right','start','end','auto'])===-1){expandFrom='auto';}if(expandFrom==='auto'){if($region.data('searchsuggest-expand-dir')){expandFrom=$region.data('searchsuggest-expand-dir');}else{regionWidth=$region.outerWidth();docWidth=$(document).width();if((regionWidth/docWidth)>0.85){expandFrom='start';}else{regionCenter=$region.offset().left+regionWidth/2;docCenter=docWidth/2;if(Math.abs(regionCenter-docCenter)/docCenter<0.10){expandFrom='start';}else{expandFrom=regionCenter>docCenter?'right':'left';}}}}if(expandFrom==='start'){expandFrom=docDir==='rtl'?'right':'left';}else if(expandFrom==='end'){expandFrom=docDir==='rtl'?'left':'right';}return expandFrom;}(context.config.expandFrom));if(context.config.expandFrom==='left'){newCSS.left=context.config.$region.offset().left;newCSS.right='auto';}else{newCSS.left='auto';newCSS.right=$(document).width()-(context.config.$region.offset().left+context.config.$region.outerWidth());}context.data.$container.css(newCSS);$results=context
.data.$container.children('.suggestions-results');$results.empty();expWidth=-1;$autoEllipseMe=$([]);matchedText=null;for(i=0;i<context.config.suggestions.length;i++){text=context.config.suggestions[i];$result=$('<div>').addClass('suggestions-result').attr('rel',i).data('text',context.config.suggestions[i]).mousemove(function(){context.data.selectedWithMouse=true;$.suggestions.highlight(context,$(this).closest('.suggestions-results .suggestions-result'),false);}).appendTo($results);if(typeof context.config.result.render==='function'){context.config.result.render.call($result,context.config.suggestions[i],context);}else{$result.append($('<span>').css('whiteSpace','nowrap').text(text));}if(context.config.highlightInput){matchedText=context.data.prevText;}childrenWidth=$result.children().outerWidth();if(childrenWidth>$result.width()&&childrenWidth>expWidth){expWidth=childrenWidth+(context.data.$container.width()-$result.width());}$autoEllipseMe=$autoEllipseMe.add($result);}if(expWidth>
context.data.$container.width()){maxWidth=context.config.maxExpandFactor*context.data.$textbox.width();context.data.$container.width(Math.min(expWidth,maxWidth));}$autoEllipseMe.autoEllipsis({hasSpan:true,tooltip:true,matchText:matchedText});}}break;case'maxRows':context.config[property]=Math.max(1,Math.min(100,value));break;case'delay':context.config[property]=Math.max(0,Math.min(1200,value));break;case'maxExpandFactor':context.config[property]=Math.max(1,value);break;case'submitOnClick':case'positionFromLeft':case'highlightInput':context.config[property]=value?true:false;break;}},highlight:function(context,result,updateTextbox){var selected=context.data.$container.find('.suggestions-result-current');if(!result.get||selected.get(0)!==result.get(0)){if(result==='prev'){if(selected.hasClass('suggestions-special')){result=context.data.$container.find('.suggestions-result:last');}else{result=selected.prev();if(!(result.length&&result.hasClass('suggestions-result'))){result=selected.
parents('.suggestions-results > *').prev().find('.suggestions-result').eq(0);}if(selected.length===0){if(context.data.$container.find('.suggestions-special').html()!==''){result=context.data.$container.find('.suggestions-special');}else{result=context.data.$container.find('.suggestions-results .suggestions-result:last');}}}}else if(result==='next'){if(selected.length===0){result=context.data.$container.find('.suggestions-results .suggestions-result:first');if(result.length===0&&context.data.$container.find('.suggestions-special').html()!==''){result=context.data.$container.find('.suggestions-special');}}else{result=selected.next();if(!(result.length&&result.hasClass('suggestions-result'))){result=selected.parents('.suggestions-results > *').next().find('.suggestions-result').eq(0);}if(selected.hasClass('suggestions-special')){result=$([]);}else if(result.length===0&&context.data.$container.find('.suggestions-special').html()!==''){result=context.data.$container.find(
'.suggestions-special');}}}selected.removeClass('suggestions-result-current');result.addClass('suggestions-result-current');}if(updateTextbox){if(result.length===0||result.is('.suggestions-special')){$.suggestions.restore(context);}else{context.data.$textbox.val(result.data('text'));context.data.$textbox.change();}context.data.$textbox.trigger('change');}},keypress:function(e,context,key){var selected,wasVisible=context.data.$container.is(':visible'),preventDefault=false;switch(key){case 40:if(wasVisible){$.suggestions.highlight(context,'next',true);context.data.selectedWithMouse=false;}else{$.suggestions.update(context,false);}preventDefault=true;break;case 38:if(wasVisible){$.suggestions.highlight(context,'prev',true);context.data.selectedWithMouse=false;}preventDefault=wasVisible;break;case 27:context.data.$container.hide();$.suggestions.restore(context);$.suggestions.cancel(context);context.data.$textbox.trigger('change');preventDefault=wasVisible;break;case 13:context.data.
$container.hide();preventDefault=wasVisible;selected=context.data.$container.find('.suggestions-result-current');if(selected.length===0||context.data.selectedWithMouse){$.suggestions.cancel(context);context.config.$region.closest('form').submit();}else if(selected.is('.suggestions-special')){if(typeof context.config.special.select==='function'){context.config.special.select.call(selected,context.data.$textbox);}}else{if(typeof context.config.result.select==='function'){$.suggestions.highlight(context,selected,true);context.config.result.select.call(selected,context.data.$textbox);}else{$.suggestions.highlight(context,selected,true);}}break;default:$.suggestions.update(context,true);break;}if(preventDefault){e.preventDefault();e.stopImmediatePropagation();}}};$.fn.suggestions=function(){var returnValue,args=arguments;$(this).each(function(){var context,key;context=$(this).data('suggestions-context');if(context===undefined||context===null){context={config:{fetch:function(){},cancel:
function(){},special:{},result:{},$region:$(this),suggestions:[],maxRows:7,delay:120,submitOnClick:false,maxExpandFactor:3,expandFrom:'auto',highlightInput:false}};}if(args.length>0){if(typeof args[0]==='object'){for(key in args[0]){$.suggestions.configure(context,key,args[0][key]);}}else if(typeof args[0]==='string'){if(args.length>1){$.suggestions.configure(context,args[0],args[1]);}else if(returnValue===null||returnValue===undefined){returnValue=(args[0]in context.config?undefined:context.config[args[0]]);}}}if(context.data===undefined){context.data={timerID:null,prevText:null,visibleResults:0,mouseDownOn:$([]),$textbox:$(this),selectedWithMouse:false};context.data.$container=$('<div>').css('display','none').addClass('suggestions').append($('<div>').addClass('suggestions-results').mousedown(function(e){context.data.mouseDownOn=$(e.target).closest('.suggestions-results .suggestions-result');}).mouseup(function(e){var $result=$(e.target).closest(
'.suggestions-results .suggestions-result'),$other=context.data.mouseDownOn;context.data.mouseDownOn=$([]);if($result.get(0)!==$other.get(0)){return;}if(!(e.which!==1||e.altKey||e.ctrlKey||e.shiftKey||e.metaKey)){$.suggestions.highlight(context,$result,true);context.data.$container.hide();if(typeof context.config.result.select==='function'){context.config.result.select.call($result,context.data.$textbox);}}context.data.$textbox.focus();})).append($('<div>').addClass('suggestions-special').mousedown(function(e){context.data.mouseDownOn=$(e.target).closest('.suggestions-special');}).mouseup(function(e){var $special=$(e.target).closest('.suggestions-special'),$other=context.data.mouseDownOn;context.data.mouseDownOn=$([]);if($special.get(0)!==$other.get(0)){return;}if(!(e.which!==1||e.altKey||e.ctrlKey||e.shiftKey||e.metaKey)){context.data.$container.hide();if(typeof context.config.special.select==='function'){context.config.special.select.call($special,context.data.$textbox);}}context.
data.$textbox.focus();}).mousemove(function(e){context.data.selectedWithMouse=true;$.suggestions.highlight(context,$(e.target).closest('.suggestions-special'),false);})).appendTo($('body'));$(this).attr('autocomplete','off').keydown(function(e){context.data.keypressed=e.which;context.data.keypressedCount=0;switch(context.data.keypressed){case 40:e.preventDefault();e.stopImmediatePropagation();break;case 38:case 27:case 13:if(context.data.$container.is(':visible')){e.preventDefault();e.stopImmediatePropagation();}}}).keypress(function(e){context.data.keypressedCount++;$.suggestions.keypress(e,context,context.data.keypressed);}).keyup(function(e){if(context.data.keypressedCount===0){$.suggestions.keypress(e,context,context.data.keypressed);}}).blur(function(){if(context.data.mouseDownOn.length>0){return;}context.data.$container.hide();$.suggestions.cancel(context);});}$(this).data('suggestions-context',context);});return returnValue!==undefined?returnValue:$(this);};}(jQuery));;},{"css":
[
".suggestions{overflow:hidden;position:absolute;top:0;left:0;width:0;border:none;z-index:1099;padding:0;margin:-1px -1px 0 0} html \u003E body .suggestions{margin:-1px 0 0 0}.suggestions-special{position:relative;background-color:white;cursor:pointer;border:solid 1px #aaaaaa;padding:0;margin:0;margin-top:-2px;display:none;padding:0.25em 0.25em;line-height:1.25em}.suggestions-results{background-color:white;cursor:pointer;border:solid 1px #aaaaaa;padding:0;margin:0}.suggestions-result{color:black;margin:0;line-height:1.5em;padding:0.01em 0.25em;text-align:left}.suggestions-result-current{background-color:#4C59A6;color:white}.suggestions-special .special-label{color:gray;text-align:left}.suggestions-special .special-query{color:black;font-style:italic;text-align:left}.suggestions-special .special-hover{background-color:silver}.suggestions-result-current .special-label,.suggestions-result-current .special-query{color:white}.autoellipsis-matched,.highlight{font-weight:bold}\n/* cache key: winamp_wiki:resourceloader:filter:minify-css:7:9780324491b653a3780e2d029bdc140c */"
]},{});mw.loader.implement("jquery.tabIndex",function(){(function($){$.fn.firstTabIndex=function(){var minTabIndex=null;$(this).find('[tabindex]').each(function(){var tabIndex=parseInt($(this).prop('tabindex'),10);if(tabIndex>0&&!isNaN(tabIndex)){if(minTabIndex===null){minTabIndex=tabIndex;}else if(tabIndex<minTabIndex){minTabIndex=tabIndex;}}});return minTabIndex;};$.fn.lastTabIndex=function(){var maxTabIndex=null;$(this).find('[tabindex]').each(function(){var tabIndex=parseInt($(this).prop('tabindex'),10);if(tabIndex>0&&!isNaN(tabIndex)){if(maxTabIndex===null){maxTabIndex=tabIndex;}else if(tabIndex>maxTabIndex){maxTabIndex=tabIndex;}}});return maxTabIndex;};}(jQuery));;},{},{});mw.loader.implement("mediawiki.action.view.postEdit",function(){(function(mw,$){'use strict';var config=mw.config.get(['wgAction','wgCookiePrefix','wgCurRevisionId']),cookieKey=config.wgCookiePrefix+'PostEditRevision'+config.wgCurRevisionId,$div,id;function showConfirmation(data){data=data||{};if(data.message
===undefined){data.message=$.parseHTML(mw.message('postedit-confirmation',data.user||mw.user).escaped());}$div=$('<div class="postedit-container">'+'<div class="postedit">'+'<div class="postedit-icon postedit-icon-checkmark postedit-content"></div>'+'<a href="#" class="postedit-close">&times;</a>'+'</div>'+'</div>');if(typeof data.message==='string'){$div.find('.postedit-content').text(data.message);}else if(typeof data.message==='object'){$div.find('.postedit-content').append(data.message);}$div.click(fadeOutConfirmation).prependTo('body');id=setTimeout(fadeOutConfirmation,3000);}function fadeOutConfirmation(){clearTimeout(id);$div.find('.postedit').addClass('postedit postedit-faded');setTimeout(removeConfirmation,500);return false;}function removeConfirmation(){$div.remove();mw.hook('postEdit.afterRemoval').fire();}mw.hook('postEdit').add(showConfirmation);if(config.wgAction==='view'&&$.cookie(cookieKey)==='1'){$.cookie(cookieKey,null,{path:'/'});mw.config.set('wgPostEdit',true);mw.
hook('postEdit').fire();}}(mediaWiki,jQuery));;},{"css":[
".postedit-container{margin:0 auto;position:fixed;top:0;height:0;left:50%;z-index:1000;font-size:13px}.postedit-container:hover{cursor:pointer}.postedit{position:relative;top:0.6em;left:-50%;padding:.6em 3.6em .6em 1.1em;line-height:1.5625em;color:#626465;background-color:#f4f4f4;border:1px solid #dcd9d9;text-shadow:0 0.0625em 0 rgba(255,255,255,0.5);border-radius:5px;-webkit-box-shadow:0 2px 5px 0 #ccc;box-shadow:0 2px 5px 0 #ccc;-webkit-transition:all 0.25s ease-in-out;-moz-transition:all 0.25s ease-in-out;-ms-transition:all 0.25s ease-in-out;-o-transition:all 0.25s ease-in-out;transition:all 0.25s ease-in-out}.skin-monobook .postedit{top:6em !important}.postedit-faded{opacity:0}.postedit-icon{padding-left:41px;  line-height:25px;background-repeat:no-repeat;background-position:8px 50%}.postedit-icon-checkmark{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABblBMVEUAAAD///////9PfTf///80aRdTgjn///9Feij///////////9Rfzf///////////9PfjZRgDh1o1xOfTb///////+bwYqLtnj///////9PfTa82K////9WhT6YxIL///9QgDdTgzr////////j7uDl7eLq8efi693k7OH///////9UhjuBr2rp9uRUhjr///9YljVKgir///9WiTlYjT3////9/v57vFlbkT5PjC9dlD/5/fhuq09stUTs9uhxuElctCpfnT1huDFloEZloUZmpENmvDZpvDxpvTxqvjxrvT5rvT9rwTxsqktswD5uwkBvuUdxw0NztFBztU9ztVBzwkp0tlJ1xkd2t1R3uVR4w1F4xk54x014yE15uVZ5v1R5xVB6v1R7yFJ8wVh9xVl9yFR9yVd9ylN+xVh+yFd/x1l/yFeAylmEx1+Ny2uY0Hqe04Wj1Ymv3Ze33qLD47TJ5L3O6cPU7Mrq9eb2+/Q4j37OAAAAQHRSTlMAAQIEBAUFBQwPFB4fJCUoKiosQEhJS01RUlZZXmdydXaChYuSlJSWmJmoq6uur8LExcvM19fg5ejt8fX2+Pr7SljgewAAAKpJREFUGBkFwQNCAwAAAMDLtl3LtrG4rWXbtvX77gAgZ6grFwC0bhwNVgKgdPZx8b0dgLi+s7Wn0VoAqpfOI9+BNADZI7fLrz2pSEwGHZuH+78lSK8ZLkLezF3ooyUG3VPXq2USei9WngeyoG195yBYWDF3E/2pAhl1e9Gr8bGT+bfOFCC2fnvh4X7rcqIAQNNu+HT6sxkAjceTL/2ZAIhv+PorBwBJxfkA//dFHSCBy/UTAAAAAElFTkSuQmCC);background-image:url(/resources/mediawiki.action/images/green-checkmark.png?2014-02-27T23:46:40Z)!ie;background-position:left}.postedit-close{position:absolute;padding:0 .8em;right:0;top:0;font-size:1.25em;font-weight:bold;line-height:2.3em;color:black;text-shadow:0 0.0625em 0 white;text-decoration:none;opacity:0.2;filter:alpha(opacity=20)}.postedit-close:hover{color:black;text-decoration:none;opacity:0.4;filter:alpha(opacity=40)}\n/* cache key: winamp_wiki:resourceloader:filter:minify-css:7:5a476d5625da53616d9e8455fa1bf3c7 */"
]},{});mw.loader.implement("mediawiki.api",function(){(function(mw,$){var defaultOptions={parameters:{action:'query',format:'json'},ajax:{url:mw.util.wikiScript('api'),timeout:30*1000,dataType:'json'}},tokenCache={};mw.Api=function(options){if(options===undefined){options={};}if(options.ajax&&options.ajax.url!==undefined){options.ajax.url=String(options.ajax.url);}options.parameters=$.extend({},defaultOptions.parameters,options.parameters);options.ajax=$.extend({},defaultOptions.ajax,options.ajax);this.defaults=options;};mw.Api.prototype={normalizeAjaxOptions:function(arg){var opts=arg||{};if(typeof arg==='function'){opts={ok:arg};}return opts;},get:function(parameters,ajaxOptions){ajaxOptions=this.normalizeAjaxOptions(ajaxOptions);ajaxOptions.type='GET';return this.ajax(parameters,ajaxOptions);},post:function(parameters,ajaxOptions){ajaxOptions=this.normalizeAjaxOptions(ajaxOptions);ajaxOptions.type='POST';return this.ajax(parameters,ajaxOptions);},ajax:function(parameters,ajaxOptions
){var token,apiDeferred=$.Deferred(),xhr;parameters=$.extend({},this.defaults.parameters,parameters);ajaxOptions=$.extend({},this.defaults.ajax,ajaxOptions);if(parameters.token){token=parameters.token;delete parameters.token;}ajaxOptions.data=$.param(parameters).replace(/\./g,'%2E');if(token){ajaxOptions.data+='&token='+encodeURIComponent(token);}if(ajaxOptions.ok){apiDeferred.done(ajaxOptions.ok);delete ajaxOptions.ok;}if(ajaxOptions.err){apiDeferred.fail(ajaxOptions.err);delete ajaxOptions.err;}xhr=$.ajax(ajaxOptions).fail(function(xhr,textStatus,exception){apiDeferred.reject('http',{xhr:xhr,textStatus:textStatus,exception:exception});}).done(function(result){if(result===undefined||result===null||result===''){apiDeferred.reject('ok-but-empty','OK response but empty result (check HTTP headers?)');}else if(result.error){var code=result.error.code===undefined?'unknown':result.error.code;apiDeferred.reject(code,result);}else{apiDeferred.resolve(result);}});return apiDeferred.promise({
abort:xhr.abort}).fail(function(code,details){mw.log('mw.Api error: ',code,details);});},postWithToken:function(tokenType,params){var api=this,hasOwn=tokenCache.hasOwnProperty;if(hasOwn.call(tokenCache,tokenType)&&tokenCache[tokenType]!==undefined){params.token=tokenCache[tokenType];return api.post(params).then(null,function(code){if(code==='badtoken'){tokenCache[tokenType]=params.token=undefined;return api.post(params);}return this;});}else{return api.getToken(tokenType).then(function(token){tokenCache[tokenType]=params.token=token;return api.post(params);});}},getToken:function(type){var apiPromise,d=$.Deferred();apiPromise=this.get({action:'tokens',type:type},{}).done(function(data){if(data.tokens&&data.tokens[type+'token']){d.resolve(data.tokens[type+'token']);}else{d.reject('token-missing',data);}}).fail(d.reject);return d.promise({abort:apiPromise.abort});}};mw.Api.errors=['ok-but-empty','timeout','duplicate','duplicate-archive','noimageinfo','uploaddisabled','nomodule',
'mustbeposted','badaccess-groups','stashfailed','missingresult','missingparam','invalid-file-key','copyuploaddisabled','mustbeloggedin','empty-file','file-too-large','filetype-missing','filetype-banned','filetype-banned-type','filename-tooshort','illegal-filename','verification-error','hookaborted','unknown-error','internal-error','overwrite','badtoken','fetchfileerror','fileexists-shared-forbidden','invalidtitle','notloggedin'];mw.Api.warnings=['duplicate','exists'];}(mediaWiki,jQuery));;},{},{});mw.loader.implement("mediawiki.cldr",function(){(function(mw){'use strict';var cldr={getPluralForm:function(number,pluralRules){var i;for(i=0;i<pluralRules.length;i++){if(mw.libs.pluralRuleParser(pluralRules[i],number)){break;}}return i;}};mw.cldr=cldr;}(mediaWiki));;},{},{});mw.loader.implement("mediawiki.hidpi",function(){jQuery(function($){$('body').hidpi();});;},{},{});mw.loader.implement("mediawiki.jqueryMsg",function(){(function(mw,$){var oldParser,slice=Array.prototype.slice,
parserDefaults={magic:{'SITENAME':mw.config.get('wgSiteName')},allowedHtmlElements:['b','i'],allowedHtmlCommonAttributes:['id','class','style','lang','dir','title','role'],allowedHtmlAttributesByElement:{},messages:mw.messages,language:mw.language,format:'parse'};function appendWithoutParsing($parent,children){var i,len;if(!$.isArray(children)){children=[children];}for(i=0,len=children.length;i<len;i++){if(typeof children[i]!=='object'){children[i]=document.createTextNode(children[i]);}}return $parent.append(children);}function decodePrimaryHtmlEntities(encoded){return encoded.replace(/&#039;/g,'\'').replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');}function getFailableParserFn(options){var parser=new mw.jqueryMsg.parser(options);return function(args){var key=args[0],argsArray=$.isArray(args[1])?args[1]:slice.call(args,1);try{return parser.parse(key,argsArray);}catch(e){return $('<span>').text(key+': '+e.message);}};}mw.jqueryMsg={};mw.jqueryMsg.
getMessageFunction=function(options){var failableParserFn=getFailableParserFn(options),format;if(options&&options.format!==undefined){format=options.format;}else{format=parserDefaults.format;}return function(){var failableResult=failableParserFn(arguments);if(format==='text'||format==='escaped'){return failableResult.text();}else{return failableResult.html();}};};mw.jqueryMsg.getPlugin=function(options){var failableParserFn=getFailableParserFn(options);return function(){var $target=this.empty();$.each(failableParserFn(arguments).contents(),function(i,node){appendWithoutParsing($target,node);});return $target;};};mw.jqueryMsg.parser=function(options){this.settings=$.extend({},parserDefaults,options);this.settings.onlyCurlyBraceTransform=(this.settings.format==='text'||this.settings.format==='escaped');this.emitter=new mw.jqueryMsg.htmlEmitter(this.settings.language,this.settings.magic);};mw.jqueryMsg.parser.prototype={astCache:{},parse:function(key,replacements){return this.emitter.emit
(this.getAst(key),replacements);},getAst:function(key){var cacheKey=[key,this.settings.onlyCurlyBraceTransform].join(':'),wikiText;if(this.astCache[cacheKey]===undefined){wikiText=this.settings.messages.get(key);if(typeof wikiText!=='string'){wikiText='\\['+key+'\\]';}this.astCache[cacheKey]=this.wikiTextToAst(wikiText);}return this.astCache[cacheKey];},wikiTextToAst:function(input){var pos,settings=this.settings,concat=Array.prototype.concat,regularLiteral,regularLiteralWithoutBar,regularLiteralWithoutSpace,regularLiteralWithSquareBrackets,doubleQuote,singleQuote,backslash,anyCharacter,asciiAlphabetLiteral,escapedOrLiteralWithoutSpace,escapedOrLiteralWithoutBar,escapedOrRegularLiteral,whitespace,dollar,digits,htmlDoubleQuoteAttributeValue,htmlSingleQuoteAttributeValue,htmlAttributeEquals,openHtmlStartTag,optionalForwardSlash,openHtmlEndTag,closeHtmlTag,openExtlink,closeExtlink,wikilinkPage,wikilinkContents,openWikilink,closeWikilink,templateName,pipe,colon,templateContents,
openTemplate,closeTemplate,nonWhitespaceExpression,paramExpression,expression,curlyBraceTransformExpression,result;pos=0;function choice(ps){return function(){var i,result;for(i=0;i<ps.length;i++){result=ps[i]();if(result!==null){return result;}}return null;};}function sequence(ps){var i,res,originalPos=pos,result=[];for(i=0;i<ps.length;i++){res=ps[i]();if(res===null){pos=originalPos;return null;}result.push(res);}return result;}function nOrMore(n,p){return function(){var originalPos=pos,result=[],parsed=p();while(parsed!==null){result.push(parsed);parsed=p();}if(result.length<n){pos=originalPos;return null;}return result;};}function transform(p,fn){return function(){var result=p();return result===null?null:fn(result);};}function makeStringParser(s){var len=s.length;return function(){var result=null;if(input.substr(pos,len)===s){result=s;pos+=len;}return result;};}function makeRegexParser(regex){return function(){var matches=input.substr(pos).match(regex);if(matches===null){return null
;}pos+=matches[0].length;return matches[0];};}regularLiteral=makeRegexParser(/^[^{}\[\]$<\\]/);regularLiteralWithoutBar=makeRegexParser(/^[^{}\[\]$\\|]/);regularLiteralWithoutSpace=makeRegexParser(/^[^{}\[\]$\s]/);regularLiteralWithSquareBrackets=makeRegexParser(/^[^{}$\\]/);backslash=makeStringParser('\\');doubleQuote=makeStringParser('"');singleQuote=makeStringParser('\'');anyCharacter=makeRegexParser(/^./);openHtmlStartTag=makeStringParser('<');optionalForwardSlash=makeRegexParser(/^\/?/);openHtmlEndTag=makeStringParser('</');htmlAttributeEquals=makeRegexParser(/^\s*=\s*/);closeHtmlTag=makeRegexParser(/^\s*>/);function escapedLiteral(){var result=sequence([backslash,anyCharacter]);return result===null?null:result[1];}escapedOrLiteralWithoutSpace=choice([escapedLiteral,regularLiteralWithoutSpace]);escapedOrLiteralWithoutBar=choice([escapedLiteral,regularLiteralWithoutBar]);escapedOrRegularLiteral=choice([escapedLiteral,regularLiteral]);function literalWithoutSpace(){var result=
nOrMore(1,escapedOrLiteralWithoutSpace)();return result===null?null:result.join('');}function literalWithoutBar(){var result=nOrMore(1,escapedOrLiteralWithoutBar)();return result===null?null:result.join('');}function unescapedLiteralWithoutBar(){var result=nOrMore(1,regularLiteralWithoutBar)();return result===null?null:result.join('');}function literal(){var result=nOrMore(1,escapedOrRegularLiteral)();return result===null?null:result.join('');}function curlyBraceTransformExpressionLiteral(){var result=nOrMore(1,regularLiteralWithSquareBrackets)();return result===null?null:result.join('');}asciiAlphabetLiteral=makeRegexParser(/[A-Za-z]+/);htmlDoubleQuoteAttributeValue=makeRegexParser(/^[^"]*/);htmlSingleQuoteAttributeValue=makeRegexParser(/^[^']*/);whitespace=makeRegexParser(/^\s+/);dollar=makeStringParser('$');digits=makeRegexParser(/^\d+/);function replacement(){var result=sequence([dollar,digits]);if(result===null){return null;}return['REPLACE',parseInt(result[1],10)-1];}openExtlink=
makeStringParser('[');closeExtlink=makeStringParser(']');function extlink(){var result,parsedResult;result=null;parsedResult=sequence([openExtlink,nonWhitespaceExpression,whitespace,nOrMore(1,expression),closeExtlink]);if(parsedResult!==null){result=['EXTLINK',parsedResult[1]];if(parsedResult[3].length===1){result.push(parsedResult[3][0]);}else{result.push(['CONCAT'].concat(parsedResult[3]));}}return result;}function extLinkParam(){var result=sequence([openExtlink,dollar,digits,whitespace,expression,closeExtlink]);if(result===null){return null;}return['EXTLINKPARAM',parseInt(result[2],10)-1,result[4]];}openWikilink=makeStringParser('[[');closeWikilink=makeStringParser(']]');pipe=makeStringParser('|');function template(){var result=sequence([openTemplate,templateContents,closeTemplate]);return result===null?null:result[1];}wikilinkPage=choice([unescapedLiteralWithoutBar,template]);function pipedWikilink(){var result=sequence([wikilinkPage,pipe,expression]);return result===null?null:[
result[0],result[2]];}wikilinkContents=choice([pipedWikilink,wikilinkPage]);function wikilink(){var result,parsedResult,parsedLinkContents;result=null;parsedResult=sequence([openWikilink,wikilinkContents,closeWikilink]);if(parsedResult!==null){parsedLinkContents=parsedResult[1];result=['WIKILINK'].concat(parsedLinkContents);}return result;}function doubleQuotedHtmlAttributeValue(){var parsedResult=sequence([doubleQuote,htmlDoubleQuoteAttributeValue,doubleQuote]);return parsedResult===null?null:parsedResult[1];}function singleQuotedHtmlAttributeValue(){var parsedResult=sequence([singleQuote,htmlSingleQuoteAttributeValue,singleQuote]);return parsedResult===null?null:parsedResult[1];}function htmlAttribute(){var parsedResult=sequence([whitespace,asciiAlphabetLiteral,htmlAttributeEquals,choice([doubleQuotedHtmlAttributeValue,singleQuotedHtmlAttributeValue])]);return parsedResult===null?null:[parsedResult[1],parsedResult[3]];}function isAllowedHtml(startTagName,endTagName,attributes){var i,
len,attributeName;startTagName=startTagName.toLowerCase();endTagName=endTagName.toLowerCase();if(startTagName!==endTagName||$.inArray(startTagName,settings.allowedHtmlElements)===-1){return false;}for(i=0,len=attributes.length;i<len;i+=2){attributeName=attributes[i];if($.inArray(attributeName,settings.allowedHtmlCommonAttributes)===-1&&$.inArray(attributeName,settings.allowedHtmlAttributesByElement[startTagName]||[])===-1){return false;}}return true;}function htmlAttributes(){var parsedResult=nOrMore(0,htmlAttribute)();return concat.apply(['HTMLATTRIBUTES'],parsedResult);}function html(){var result=null,parsedOpenTagResult,parsedHtmlContents,parsedCloseTagResult,wrappedAttributes,attributes,startTagName,endTagName,startOpenTagPos,startCloseTagPos,endOpenTagPos,endCloseTagPos;startOpenTagPos=pos;parsedOpenTagResult=sequence([openHtmlStartTag,asciiAlphabetLiteral,htmlAttributes,optionalForwardSlash,closeHtmlTag]);if(parsedOpenTagResult===null){return null;}endOpenTagPos=pos;startTagName=
parsedOpenTagResult[1];parsedHtmlContents=nOrMore(0,expression)();startCloseTagPos=pos;parsedCloseTagResult=sequence([openHtmlEndTag,asciiAlphabetLiteral,closeHtmlTag]);if(parsedCloseTagResult===null){return['CONCAT',input.substring(startOpenTagPos,endOpenTagPos)].concat(parsedHtmlContents);}endCloseTagPos=pos;endTagName=parsedCloseTagResult[1];wrappedAttributes=parsedOpenTagResult[2];attributes=wrappedAttributes.slice(1);if(isAllowedHtml(startTagName,endTagName,attributes)){result=['HTMLELEMENT',startTagName,wrappedAttributes].concat(parsedHtmlContents);}else{result=['CONCAT',input.substring(startOpenTagPos,endOpenTagPos)].concat(parsedHtmlContents,input.substring(startCloseTagPos,endCloseTagPos));}return result;}templateName=transform(makeRegexParser(/^[ !"$&'()*,.\/0-9;=?@A-Z\^_`a-z~\x80-\xFF+\-]+/),function(result){return result.toString();});function templateParam(){var expr,result;result=sequence([pipe,nOrMore(0,paramExpression)]);if(result===null){return null;}expr=result[1];
return expr.length>1?['CONCAT'].concat(expr):expr[0];}function templateWithReplacement(){var result=sequence([templateName,colon,replacement]);return result===null?null:[result[0],result[2]];}function templateWithOutReplacement(){var result=sequence([templateName,colon,paramExpression]);return result===null?null:[result[0],result[2]];}colon=makeStringParser(':');templateContents=choice([function(){var res=sequence([choice([templateWithReplacement,templateWithOutReplacement]),nOrMore(0,templateParam)]);return res===null?null:res[0].concat(res[1]);},function(){var res=sequence([templateName,nOrMore(0,templateParam)]);if(res===null){return null;}return[res[0]].concat(res[1]);}]);openTemplate=makeStringParser('{{');closeTemplate=makeStringParser('}}');nonWhitespaceExpression=choice([template,wikilink,extLinkParam,extlink,replacement,literalWithoutSpace]);paramExpression=choice([template,wikilink,extLinkParam,extlink,replacement,literalWithoutBar]);expression=choice([template,wikilink,
extLinkParam,extlink,replacement,html,literal]);curlyBraceTransformExpression=choice([template,replacement,curlyBraceTransformExpressionLiteral]);function start(rootExpression){var result=nOrMore(0,rootExpression)();if(result===null){return null;}return['CONCAT'].concat(result);}result=start(this.settings.onlyCurlyBraceTransform?curlyBraceTransformExpression:expression);if(result===null||pos!==input.length){throw new Error('Parse error at position '+pos.toString()+' in input: '+input);}return result;}};mw.jqueryMsg.htmlEmitter=function(language,magic){this.language=language;var jmsg=this;$.each(magic,function(key,val){jmsg[key.toLowerCase()]=function(){return val;};});this.emit=function(node,replacements){var ret,subnodes,operation,jmsg=this;switch(typeof node){case'string':case'number':ret=node;break;case'object':subnodes=$.map(node.slice(1),function(n){return jmsg.emit(n,replacements);});operation=node[0].toLowerCase();if(typeof jmsg[operation]==='function'){ret=jmsg[operation](
subnodes,replacements);}else{throw new Error('Unknown operation "'+operation+'"');}break;case'undefined':ret='';break;default:throw new Error('Unexpected type in AST: '+typeof node);}return ret;};};mw.jqueryMsg.htmlEmitter.prototype={concat:function(nodes){var $span=$('<span>').addClass('mediaWiki_htmlEmitter');$.each(nodes,function(i,node){if(node instanceof jQuery&&node.hasClass('mediaWiki_htmlEmitter')){$.each(node.contents(),function(j,childNode){appendWithoutParsing($span,childNode);});}else{appendWithoutParsing($span,node);}});return $span;},replace:function(nodes,replacements){var index=parseInt(nodes[0],10);if(index<replacements.length){return replacements[index];}else{return'$'+(index+1);}},wikilink:function(nodes){var page,anchor,url;page=nodes[0];url=mw.util.getUrl(page);if(nodes.length===1){anchor=page;}else{anchor=nodes[1];}return $('<a />').attr({title:page,href:url}).text(anchor);},htmlattributes:function(nodes){var i,len,mapping={};for(i=0,len=nodes.length;i<len;i+=2){
mapping[nodes[i]]=decodePrimaryHtmlEntities(nodes[i+1]);}return mapping;},htmlelement:function(nodes){var tagName,attributes,contents,$element;tagName=nodes.shift();attributes=nodes.shift();contents=nodes;$element=$(document.createElement(tagName)).attr(attributes);return appendWithoutParsing($element,contents);},extlink:function(nodes){var $el,arg=nodes[0],contents=nodes[1];if(arg instanceof jQuery){$el=arg;}else{$el=$('<a>');if(typeof arg==='function'){$el.click(arg).attr('href','#');}else{$el.attr('href',arg.toString());}}return appendWithoutParsing($el,contents);},extlinkparam:function(nodes,replacements){var replacement,index=parseInt(nodes[0],10);if(index<replacements.length){replacement=replacements[index];}else{replacement='$'+(index+1);}return this.extlink([replacement,nodes[1]]);},plural:function(nodes){var forms,count;count=parseFloat(this.language.convertNumber(nodes[0],true));forms=nodes.slice(1);return forms.length?this.language.convertPlural(count,forms):'';},gender:
function(nodes){var gender,forms;if(nodes[0]&&nodes[0].options instanceof mw.Map){gender=nodes[0].options.get('gender');}else{gender=nodes[0];}forms=nodes.slice(1);return this.language.gender(gender,forms);},grammar:function(nodes){var form=nodes[0],word=nodes[1];return word&&form&&this.language.convertGrammar(word,form);},int:function(nodes){return mw.jqueryMsg.getMessageFunction()(nodes[0].toLowerCase());},formatnum:function(nodes){var isInteger=(nodes[1]&&nodes[1]==='R')?true:false,number=nodes[0];return this.language.convertNumber(number,isInteger);}};window.gM=mw.jqueryMsg.getMessageFunction();$.fn.msg=mw.jqueryMsg.getPlugin();oldParser=mw.Message.prototype.parser;mw.Message.prototype.parser=function(){var messageFunction;if(this.format==='plain'||!/\{\{|[\[<>]/.test(this.map.get(this.key))){return oldParser.apply(this);}messageFunction=mw.jqueryMsg.getMessageFunction({'messages':this.map,'format':this.format});return messageFunction(this.key,this.parameters);};}(mediaWiki,jQuery)
);;},{},{});mw.loader.implement("mediawiki.language",function(){(function(mw,$){var language={procPLURAL:function(template){if(template.title&&template.parameters&&mw.language.convertPlural){if(template.parameters.length===0){return'';}var count=mw.language.convertNumber(template.title,true);return mw.language.convertPlural(parseInt(count,10),template.parameters);}if(template.parameters[0]){return template.parameters[0];}return'';},convertPlural:function(count,forms){var pluralRules,formCount,form,index,equalsPosition,pluralFormIndex=0;if(!forms||forms.length===0){return'';}for(index=0;index<forms.length;index++){form=forms[index];if(/^\d+=/.test(form)){equalsPosition=form.indexOf('=');formCount=parseInt(form.substring(0,equalsPosition),10);if(formCount===count){return form.substr(equalsPosition+1);}forms[index]=undefined;}}forms=$.map(forms,function(form){return form;});pluralRules=mw.language.getData(mw.config.get('wgUserLanguage'),'pluralRules');if(!pluralRules){return(count===1)?
forms[0]:forms[1];}pluralFormIndex=mw.cldr.getPluralForm(count,pluralRules);pluralFormIndex=Math.min(pluralFormIndex,forms.length-1);return forms[pluralFormIndex];},preConvertPlural:function(forms,count){while(forms.length<count){forms.push(forms[forms.length-1]);}return forms;},gender:function(gender,forms){if(!forms||forms.length===0){return'';}forms=mw.language.preConvertPlural(forms,2);if(gender==='male'){return forms[0];}if(gender==='female'){return forms[1];}return(forms.length===3)?forms[2]:forms[0];},convertGrammar:function(word,form){var grammarForms=mw.language.getData(mw.config.get('wgUserLanguage'),'grammarForms');if(grammarForms&&grammarForms[form]){return grammarForms[form][word]||word;}return word;}};$.extend(mw.language,language);}(mediaWiki,jQuery));(function(mw,$){function pad(text,size,ch,end){if(!ch){ch='0';}var out=String(text),padStr=replicate(ch,Math.ceil((size-out.length)/ch.length));return end?out+padStr:padStr+out;}function replicate(str,num){if(num<=0||!str){
return'';}var buf=[];while(num){buf.push(str);str+=str;}return buf.join('');}function commafyNumber(value,pattern,options){options=options||{group:',',decimal:'.'};if(isNaN(value)){return value;}var padLength,patternDigits,index,whole,off,remainder,patternParts=pattern.split('.'),maxPlaces=(patternParts[1]||[]).length,valueParts=String(Math.abs(value)).split('.'),fractional=valueParts[1]||'',groupSize=0,groupSize2=0,pieces=[];if(patternParts[1]){padLength=(patternParts[1]&&patternParts[1].lastIndexOf('0')+1);if(padLength>fractional.length){valueParts[1]=pad(fractional,padLength,'0',true);}if(maxPlaces<fractional.length){valueParts[1]=fractional.substr(0,maxPlaces);}}else{if(valueParts[1]){valueParts.pop();}}patternDigits=patternParts[0].replace(',','');padLength=patternDigits.indexOf('0');if(padLength!==-1){padLength=patternDigits.length-padLength;if(padLength>valueParts[0].length){valueParts[0]=pad(valueParts[0],padLength);}if(patternDigits.indexOf('#')===-1){valueParts[0]=valueParts[
0].substr(valueParts[0].length-padLength);}}index=patternParts[0].lastIndexOf(',');if(index!==-1){groupSize=patternParts[0].length-index-1;remainder=patternParts[0].substr(0,index);index=remainder.lastIndexOf(',');if(index!==-1){groupSize2=remainder.length-index-1;}}for(whole=valueParts[0];whole;){off=whole.length-groupSize;pieces.push((off>0)?whole.substr(off):whole);whole=(off>0)?whole.slice(0,off):'';if(groupSize2){groupSize=groupSize2;}}valueParts[0]=pieces.reverse().join(options.group);return valueParts.join(options.decimal);}$.extend(mw.language,{convertNumber:function(num,integer){var i,tmp,transformTable,numberString,convertedNumber,pattern;pattern=mw.language.getData(mw.config.get('wgUserLanguage'),'digitGroupingPattern')||'#,##0.###';transformTable=mw.language.getDigitTransformTable();if(!transformTable){return num;}if(integer){if(parseInt(num,10)===num){return num;}tmp=[];for(i in transformTable){tmp[transformTable[i]]=i;}transformTable=tmp;numberString=num+'';}else{
numberString=mw.language.commafy(num,pattern);}convertedNumber='';for(i=0;i<numberString.length;i++){if(transformTable[numberString[i]]){convertedNumber+=transformTable[numberString[i]];}else{convertedNumber+=numberString[i];}}return integer?parseInt(convertedNumber,10):convertedNumber;},getDigitTransformTable:function(){return mw.language.getData(mw.config.get('wgUserLanguage'),'digitTransformTable')||[];},getSeparatorTransformTable:function(){return mw.language.getData(mw.config.get('wgUserLanguage'),'separatorTransformTable')||[];},commafy:function(value,pattern){var numberPattern,transformTable=mw.language.getSeparatorTransformTable(),group=transformTable[',']||',',numberPatternRE=/[#0,]*[#0](?:\.0*#*)?/,decimal=transformTable['.']||'.',patternList=pattern.split(';'),positivePattern=patternList[0];pattern=patternList[(value<0)?1:0]||('-'+positivePattern);numberPattern=positivePattern.match(numberPatternRE);if(!numberPattern){throw new Error(
'unable to find a number expression in pattern: '+pattern);}return pattern.replace(numberPatternRE,commafyNumber(value,numberPattern[0],{decimal:decimal,group:group}));}});}(mediaWiki,jQuery));;},{},{});mw.loader.implement("mediawiki.searchSuggest",function(){(function(mw,$){$(function(){var map,resultRenderCache,searchboxesSelectors,$searchRegion=$('#simpleSearch, #searchInput').first(),$searchInput=$('#searchInput');map={browsers:{ltr:{opera:[['>=',9.6]],docomo:false,blackberry:false,ipod:false,iphone:false},rtl:{opera:[['>=',9.6]],docomo:false,blackberry:false,ipod:false,iphone:false}}};if(!$.client.test(map)){return;}function computeResultRenderCache(context){var $form,formAction,baseHref,linkParams;$form=context.config.$region.closest('form');formAction=$form.attr('action');baseHref=formAction+(formAction.match(/\?/)?'&':'?');linkParams={};$.each($form.serializeArray(),function(idx,obj){linkParams[obj.name]=obj.value;});return{textParam:context.data.$textbox.attr('name'),
linkParams:linkParams,baseHref:baseHref};}function renderFunction(text,context){if(!resultRenderCache){resultRenderCache=computeResultRenderCache(context);}resultRenderCache.linkParams[resultRenderCache.textParam]=text;this.append($('<span>').css('whiteSpace','nowrap').text(text)).wrap($('<a>').attr('href',resultRenderCache.baseHref+$.param(resultRenderCache.linkParams)).addClass('mw-searchSuggest-link'));}function specialRenderFunction(query,context){var $el=this;if(!resultRenderCache){resultRenderCache=computeResultRenderCache(context);}resultRenderCache.linkParams[resultRenderCache.textParam]=query;if($el.children().length===0){$el.append($('<div>').addClass('special-label').text(mw.msg('searchsuggest-containing')),$('<div>').addClass('special-query').text(query).autoEllipsis()).show();}else{$el.find('.special-query').text(query).autoEllipsis();}if($el.parent().hasClass('mw-searchSuggest-link')){$el.parent().attr('href',resultRenderCache.baseHref+$.param(resultRenderCache.linkParams
)+'&fulltext=1');}else{$el.wrap($('<a>').attr('href',resultRenderCache.baseHref+$.param(resultRenderCache.linkParams)+'&fulltext=1').addClass('mw-searchSuggest-link'));}}searchboxesSelectors=['#searchInput','#powerSearchText','#searchText','.mw-searchInput'];$(searchboxesSelectors.join(', ')).suggestions({fetch:function(query){var $el;if(query.length!==0){$el=$(this);$el.data('request',(new mw.Api()).get({action:'opensearch',search:query,namespace:0,suggest:''}).done(function(data){$el.suggestions('suggestions',data[1]);}));}},cancel:function(){var apiPromise=$(this).data('request');if(apiPromise&&$.isFunction(apiPromise.abort)){apiPromise.abort();$(this).removeData('request');}},result:{render:renderFunction,select:function($input){$input.closest('form').submit();}},delay:120,highlightInput:true}).bind('paste cut drop',function(){$(this).trigger('keypress');});if($searchRegion.length===0){return;}$searchInput.suggestions({result:{render:renderFunction,select:function($input){$input.
closest('form').submit();}},special:{render:specialRenderFunction,select:function($input){$input.closest('form').append($('<input type="hidden" name="fulltext" value="1"/>'));$input.closest('form').submit();}},$region:$searchRegion});$searchInput.data('suggestions-context').data.$container.css('fontSize',$searchInput.css('fontSize'));});}(mediaWiki,jQuery));;},{"css":[".suggestions a.mw-searchSuggest-link,.suggestions a.mw-searchSuggest-link:hover,.suggestions a.mw-searchSuggest-link:active,.suggestions a.mw-searchSuggest-link:focus{text-decoration:none;color:black}.suggestions-result-current a.mw-searchSuggest-link,.suggestions-result-current a.mw-searchSuggest-link:hover,.suggestions-result-current a.mw-searchSuggest-link:active,.suggestions-result-current a.mw-searchSuggest-link:focus{color:white}\n/* cache key: winamp_wiki:resourceloader:filter:minify-css:7:52b1797f70c7e4094dfa4191101944e8 */"]},{});mw.loader.implement("mediawiki.user",function(){(function(mw,$){var user,callbacks=
{},options=mw.user.options||new mw.Map(),tokens=mw.user.tokens||new mw.Map();function getUserInfo(info,callback){var api;if(callbacks[info]){callbacks[info].add(callback);return;}callbacks.rights=$.Callbacks('once memory');callbacks.groups=$.Callbacks('once memory');callbacks[info].add(callback);api=new mw.Api();api.get({action:'query',meta:'userinfo',uiprop:'rights|groups'}).always(function(data){var rights,groups;if(data.query&&data.query.userinfo){rights=data.query.userinfo.rights;groups=data.query.userinfo.groups;}callbacks.rights.fire(rights||[]);callbacks.groups.fire(groups||[]);});}mw.user=user={options:options,tokens:tokens,generateRandomSessionId:function(){var i,r,id='',seed='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';for(i=0;i<32;i++){r=Math.floor(Math.random()*seed.length);id+=seed.substring(r,r+1);}return id;},getId:function(){return mw.config.get('wgUserId',0);},getName:function(){return mw.config.get('wgUserName');},name:function(){return user.
getName();},getRegistration:function(){var registration=mw.config.get('wgUserRegistration');if(user.isAnon()){return false;}else if(registration===null){return null;}else{return new Date(registration);}},isAnon:function(){return user.getName()===null;},anonymous:function(){return user.isAnon();},sessionId:function(){var sessionId=$.cookie('mediaWiki.user.sessionId');if(sessionId===undefined||sessionId===null){sessionId=user.generateRandomSessionId();$.cookie('mediaWiki.user.sessionId',sessionId,{expires:null,path:'/'});}return sessionId;},id:function(){return user.getName()||user.sessionId();},bucket:function(key,options){var cookie,parts,version,bucket,range,k,rand,total;options=$.extend({buckets:{},version:0,expires:30},options||{});cookie=$.cookie('mediaWiki.user.bucket:'+key);if(typeof cookie==='string'&&cookie.length>2&&cookie.indexOf(':')!==-1){parts=cookie.split(':');if(parts.length>1&&Number(parts[0])===options.version){version=Number(parts[0]);bucket=String(parts[1]);}}if(
bucket===undefined){if(!$.isPlainObject(options.buckets)){throw new Error('Invalid bucket. Object expected for options.buckets.');}version=Number(options.version);range=0;for(k in options.buckets){range+=options.buckets[k];}rand=Math.random()*range;total=0;for(k in options.buckets){bucket=k;total+=options.buckets[k];if(total>=rand){break;}}$.cookie('mediaWiki.user.bucket:'+key,version+':'+bucket,{path:'/',expires:Number(options.expires)});}return bucket;},getGroups:function(callback){getUserInfo('groups',callback);},getRights:function(callback){getUserInfo('rights',callback);}};}(mediaWiki,jQuery));;},{},{});mw.loader.implement("mediawiki.language.data",function(){mw.language.setData("en",{"digitTransformTable":null,"separatorTransformTable":null,"grammarForms":[],"pluralRules":["i = 1 and v = 0 @integer 1"],"digitGroupingPattern":null});},{},{});mw.loader.implement("mediawiki.language.init",function(){(function(mw){var language={data:{},getData:function(langCode,dataKey){var langData=
language.data;if(langData&&langData[langCode]instanceof mw.Map){return langData[langCode].get(dataKey);}return undefined;},setData:function(langCode,dataKey,value){var langData=language.data;if(!(langData[langCode]instanceof mw.Map)){langData[langCode]=new mw.Map();}langData[langCode].set(dataKey,value);}};mw.language=language;}(mediaWiki));;},{},{});mw.loader.implement("mediawiki.libs.pluralruleparser",function(){(function(mw){function pluralRuleParser(rule,number){rule=rule.split('@')[0].trim();if(!rule.length){return true;}var pos=0,operand,expression,relation,result,whitespace=makeRegexParser(/^\s+/),value=makeRegexParser(/^\d+/),_n_=makeStringParser('n'),_i_=makeStringParser('i'),_f_=makeStringParser('f'),_t_=makeStringParser('t'),_v_=makeStringParser('v'),_w_=makeStringParser('w'),_is_=makeStringParser('is'),_isnot_=makeStringParser('is not'),_isnot_sign_=makeStringParser('!='),_equal_=makeStringParser('='),_mod_=makeStringParser('mod'),_percent_=makeStringParser('%'),_not_=
makeStringParser('not'),_in_=makeStringParser('in'),_within_=makeStringParser('within'),_range_=makeStringParser('..'),_comma_=makeStringParser(','),_or_=makeStringParser('or'),_and_=makeStringParser('and');function debug(){}debug('pluralRuleParser',rule,number);function choice(parserSyntax){return function(){for(var i=0;i<parserSyntax.length;i++){var result=parserSyntax[i]();if(result!==null){return result;}}return null;};}function sequence(parserSyntax){var originalPos=pos;var result=[];for(var i=0;i<parserSyntax.length;i++){var res=parserSyntax[i]();if(res===null){pos=originalPos;return null;}result.push(res);}return result;}function nOrMore(n,p){return function(){var originalPos=pos;var result=[];var parsed=p();while(parsed!==null){result.push(parsed);parsed=p();}if(result.length<n){pos=originalPos;return null;}return result;};}function makeStringParser(s){var len=s.length;return function(){var result=null;if(rule.substr(pos,len)===s){result=s;pos+=len;}return result;};}function
makeRegexParser(regex){return function(){var matches=rule.substr(pos).match(regex);if(matches===null){return null;}pos+=matches[0].length;return matches[0];};}function i(){var result=_i_();if(result===null){debug(' -- failed i',parseInt(number,10));return result;}result=parseInt(number,10);debug(' -- passed i ',result);return result;}function n(){var result=_n_();if(result===null){debug(' -- failed n ',number);return result;}result=parseFloat(number,10);debug(' -- passed n ',result);return result;}function f(){var result=_f_();if(result===null){debug(' -- failed f ',number);return result;}result=(number+'.').split('.')[1]||0;debug(' -- passed f ',result);return result;}function t(){var result=_t_();if(result===null){debug(' -- failed t ',number);return result;}result=(number+'.').split('.')[1].replace(/0$/,'')||0;debug(' -- passed t ',result);return result;}function v(){var result=_v_();if(result===null){debug(' -- failed v ',number);return result;}result=(number+'.').split('.')[1].
length||0;debug(' -- passed v ',result);return result;}function w(){var result=_w_();if(result===null){debug(' -- failed w ',number);return result;}result=(number+'.').split('.')[1].replace(/0$/,'').length||0;debug(' -- passed w ',result);return result;}operand=choice([n,i,f,t,v,w]);expression=choice([mod,operand]);function mod(){var result=sequence([operand,whitespace,choice([_mod_,_percent_]),whitespace,value]);if(result===null){debug(' -- failed mod');return null;}debug(' -- passed '+parseInt(result[0],10)+' '+result[2]+' '+parseInt(result[4],10));return parseInt(result[0],10)%parseInt(result[4],10);}function not(){var result=sequence([whitespace,_not_]);if(result===null){debug(' -- failed not');return null;}return result[1];}function is(){var result=sequence([expression,whitespace,choice([_is_]),whitespace,value]);if(result!==null){debug(' -- passed is : '+result[0]+' == '+parseInt(result[4],10));return result[0]===parseInt(result[4],10);}debug(' -- failed is');return null;}
function isnot(){var result=sequence([expression,whitespace,choice([_isnot_,_isnot_sign_]),whitespace,value]);if(result!==null){debug(' -- passed isnot: '+result[0]+' != '+parseInt(result[4],10));return result[0]!==parseInt(result[4],10);}debug(' -- failed isnot');return null;}function not_in(){var result=sequence([expression,whitespace,_isnot_sign_,whitespace,rangeList]);if(result!==null){debug(' -- passed not_in: '+result[0]+' != '+result[4]);var range_list=result[4];for(var i=0;i<range_list.length;i++){if(parseInt(range_list[i],10)===parseInt(result[0],10)){return false;}}return true;}debug(' -- failed not_in');return null;}function rangeList(){var result=sequence([choice([range,value]),nOrMore(0,rangeTail)]);var resultList=[];if(result!==null){resultList=resultList.concat(result[0]);if(result[1][0]){resultList=resultList.concat(result[1][0]);}return resultList;}debug(' -- failed rangeList');return null;}function rangeTail(){var result=sequence([_comma_,rangeList]);if(result!==null)
{return result[1];}debug(' -- failed rangeTail');return null;}function range(){var i;var result=sequence([value,_range_,value]);if(result!==null){debug(' -- passed range');var array=[];var left=parseInt(result[0],10);var right=parseInt(result[2],10);for(i=left;i<=right;i++){array.push(i);}return array;}debug(' -- failed range');return null;}function _in(){var result=sequence([expression,nOrMore(0,not),whitespace,choice([_in_,_equal_]),whitespace,rangeList]);if(result!==null){debug(' -- passed _in:'+result);var range_list=result[5];for(var i=0;i<range_list.length;i++){if(parseInt(range_list[i],10)===parseInt(result[0],10)){return(result[1][0]!=='not');}}return(result[1][0]==='not');}debug(' -- failed _in ');return null;}function within(){var result=sequence([expression,nOrMore(0,not),whitespace,_within_,whitespace,rangeList]);if(result!==null){debug(' -- passed within');var range_list=result[5];if((result[0]>=parseInt(range_list[0],10))&&(result[0]<parseInt(range_list[range_list.length-
1],10))){return(result[1][0]!=='not');}return(result[1][0]==='not');}debug(' -- failed within ');return null;}relation=choice([is,not_in,isnot,_in,within]);function and(){var result=sequence([relation,nOrMore(0,andTail)]);if(result){if(!result[0]){return false;}for(var i=0;i<result[1].length;i++){if(!result[1][i]){return false;}}return true;}debug(' -- failed and');return null;}function andTail(){var result=sequence([whitespace,_and_,whitespace,relation]);if(result!==null){debug(' -- passed andTail'+result);return result[3];}debug(' -- failed andTail');return null;}function orTail(){var result=sequence([whitespace,_or_,whitespace,and]);if(result!==null){debug(' -- passed orTail: '+result[3]);return result[3];}debug(' -- failed orTail');return null;}function condition(){var result=sequence([and,nOrMore(0,orTail)]);if(result){for(var i=0;i<result[1].length;i++){if(result[1][i]){return true;}}return result[0];}return false;}result=condition();if(result===null){throw new Error(
'Parse error at position '+pos.toString()+' for rule: '+rule);}if(pos!==rule.length){debug('Warning: Rule not parsed completely. Parser stopped at '+rule.substr(0,pos)+' for rule: '+rule);}return result;}mw.libs.pluralRuleParser=pluralRuleParser;})(mediaWiki);;},{},{});mw.loader.implement("mediawiki.page.ready",function(){(function(mw,$){var supportsPlaceholder='placeholder'in document.createElement('input');mw.hook('wikipage.content').add(function($content){var $sortableTables;if(!supportsPlaceholder){$content.find('input[placeholder]').placeholder();}$content.find('.mw-collapsible').makeCollapsible();$sortableTables=$content.find('table.sortable');if($sortableTables.length){mw.loader.using('jquery.tablesorter',function(){$sortableTables.tablesorter();});}$content.find('input[type="checkbox"]:not(.noshiftselect)').checkboxShiftClick();});$(function(){if(!supportsPlaceholder){$('input[placeholder]').not('#mw-content-text input').placeholder();}mw.util.updateTooltipAccessKeys();});}(
mediaWiki,jQuery));;},{},{});mw.loader.implement("skins.vector.collapsibleNav",function(){(function(mw,$){'use strict';var map;function toggle($element){$.cookie('vector-nav-'+$element.parent().attr('id'),$element.parent().is('.collapsed'),{'expires':30,'path':'/'});$element.parent().toggleClass('expanded').toggleClass('collapsed').find('.body').slideToggle('fast');}map={ltr:{opera:[['>=',9.6]],konqueror:[['>=',4.0]],blackberry:false,ipod:false,iphone:false,ps3:false},rtl:{opera:[['>=',9.6]],konqueror:[['>=',4.0]],blackberry:false,ipod:false,iphone:false,ps3:false}};if(!$.client.test(map)){return true;}$(function($){var $headings,tabIndex;$('#mw-panel > .portal:first').addClass('first persistent');$('#mw-panel').addClass('collapsible-nav');$('#mw-panel > .portal:not(.persistent)').each(function(i){var id=$(this).attr('id'),state=$.cookie('vector-nav-'+id);$(this).find('h3').wrapInner($('<a href="#"></a>').click(false));if(state==='true'||(state===null&&i<1)||(state===null&&id===
'p-lang')){$(this).addClass('expanded').removeClass('collapsed').find('.body').hide().show();}else{$(this).addClass('collapsed').removeClass('expanded');}if(state!==null){$.cookie('vector-nav-'+$(this).attr('id'),state,{'expires':30,'path':'/'});}});$headings=$('#mw-panel > .portal:not(.persistent) > h3');tabIndex=$(document).lastTabIndex()+1;$('#searchInput').attr('tabindex',tabIndex++);$headings.attr('tabindex',function(){return tabIndex++;});$('#mw-panel').delegate('.portal:not(.persistent) > h3','keydown',function(e){if(e.which===13||e.which===32){toggle($(this));}}).delegate('.portal:not(.persistent) > h3','mousedown',function(e){if(e.which!==3){toggle($(this));$(this).blur();}return false;});});}(mediaWiki,jQuery));;},{},{});
/* cache key: winamp_wiki:resourceloader:filter:minify-js:7:fae73212226c3bcea49851b196fd1c3f */