.TH projectM-Jack 1 "June 24, 2010"
.SH NAME
projectM-jack \- ProjectM module for JackAudio
.SH DESCRIPTION
This manual page documents the
.B projectM-jack
command.
.PP
.B projectM-jack
provides direct visualisation of a JackAudio stream using
the projectM audio visualisation tool.
.B projectM-jack
offers a stereo-input-channel to connect Jack devices with.
.PP
.B projectM-jack
can be run from the
.B Applications
menu after it was installed.
.SH AUTHOR
projectM-Jack was written by the projectM-Team.
.PP
This manual page was written by Matthias Klumpp <matthias@tenstral.net>,
for the Debian project (and may be used by others).
