include(CheckCompilerFlag)
include(CheckLinkerFlag)

macro(enable_cflags_if_supported)
    foreach(flag ${ARGN})
        check_compiler_flag(CXX "${flag}" CXXFLAG_${flag}_SUPPORTED)
        if(CXXFLAG_${flag}_SUPPORTED)
            add_compile_options("${flag}")
        endif()
    endforeach()
endmacro()

macro(enable_linker_flags_if_supported)
    foreach(flag ${ARGN})
        check_linker_flag(CXX "${flag}" LDCFLAG_${flag}_SUPPORTED)
        if(LDCFLAG_${flag}_SUPPORTED)
            add_link_options(${flag})
        else()
            check_linker_flag(CXX "LINKER:${flag}" LDFLAG_${flag}_SUPPORTED)
            if(LDFLAG_${flag}_SUPPORTED)
                add_link_options(LINKER:${flag})
            endif()
        endif()
    endforeach()
endmacro()

macro(enable_target_linker_flags_if_supported target access)
    foreach(flag ${ARGN})
        check_linker_flag(CXX "${flag}" LDCFLAG_${flag}_SUPPORTED)
        if(LDCFLAG_${flag}_SUPPORTED)
            target_link_options(${target} ${access} ${flag})
        else()
            check_linker_flag(CXX "LINKER:${flag}" LDFLAG_${flag}_SUPPORTED)
            if(LDFLAG_${flag}_SUPPORTED)
                target_link_options(${target} ${access} LINKER:${flag})
            endif()
        endif()
    endforeach()
endmacro()
